server.port=8080
spring.datasource.url=jdbc:postgresql://postgres:5432/slashbench
spring.datasource.username=slashbench
spring.datasource.password=slashbench
spring.jackson.property-naming-strategy=SNAKE_CASE
