import http from 'k6/http'
import { check } from 'k6'

// Shared across all six stacks per CLAUDE.md §5 — do not fork per-stack copies.
// Mix: 50% point-read, 20% paginated list, 30% write (matches the "70% reads /
// 30% writes" split from the spec, with reads further split across the two
// GET endpoints so both read paths get exercised).

const BASE_URL = __ENV.BASE_URL || 'http://localhost:8080'
const RATE = parseInt(__ENV.RATE || '50', 10)
const DURATION = __ENV.DURATION || '20s'
const SEED_ROWS = parseInt(__ENV.SEED_ROWS || '100000', 10)

export const options = {
  scenarios: {
    load: {
      executor: 'constant-arrival-rate',
      rate: RATE,
      timeUnit: '1s',
      duration: DURATION,
      preAllocatedVUs: Math.max(RATE * 2, 20),
      maxVUs: Math.max(RATE * 4, 50),
    },
  },
  // p(99) isn't in k6's default summary trend stats — the SLA (CLAUDE.md §4)
  // is defined in terms of it, so the orchestrator needs it in the exported JSON.
  summaryTrendStats: ['avg', 'min', 'med', 'max', 'p(90)', 'p(95)', 'p(99)'],
}

function randomInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min
}

function parseJson(res) {
  try {
    return res.json()
  } catch {
    return null
  }
}

function seedExpectation(id) {
  return {
    name: `Item ${id}`,
    description: `Seed description for item ${id}`,
    price_cents: 100 + (id % 9000),
    quantity: 1 + (id % 500),
  }
}

export default function () {
  const roll = Math.random()

  if (roll < 0.5) {
    const id = randomInt(1, SEED_ROWS)
    const res = http.get(`${BASE_URL}/items/${id}`)
    const body = parseJson(res)
    const expected = seedExpectation(id)
    check(res, {
      'GET /items/:id status is 200': (r) => r.status === 200,
      'GET /items/:id returns the requested id': () => !!body && body.id === id,
      'GET /items/:id returns the correct seed data': () =>
        !!body &&
        body.name === expected.name &&
        body.description === expected.description &&
        body.price_cents === expected.price_cents &&
        body.quantity === expected.quantity,
    })
  } else if (roll < 0.7) {
    const page = randomInt(1, Math.floor(SEED_ROWS / 20))
    const limit = 20
    const res = http.get(`${BASE_URL}/items?page=${page}&limit=${limit}`)
    const body = parseJson(res)
    check(res, {
      'GET /items status is 200': (r) => r.status === 200,
      'GET /items returns a full page': () => !!body && Array.isArray(body.items) && body.items.length === limit,
      'GET /items reports a sane total': () => !!body && typeof body.total === 'number' && body.total >= SEED_ROWS * 0.9,
    })
  } else {
    const name = `Load Item ${Date.now()}-${randomInt(0, 999999)}`
    const description = 'generated by k6 load test'
    const priceCents = randomInt(100, 9999)
    const quantity = randomInt(1, 100)
    const payload = JSON.stringify({ name, description, price_cents: priceCents, quantity })
    const res = http.post(`${BASE_URL}/items`, payload, {
      headers: { 'Content-Type': 'application/json' },
    })
    const body = parseJson(res)
    check(res, {
      'POST /items status is 201': (r) => r.status === 201,
      'POST /items returns a real id': () => !!body && Number.isInteger(body.id) && body.id > 0,
      'POST /items echoes what was sent': () =>
        !!body && body.name === name && body.description === description && body.price_cents === priceCents && body.quantity === quantity,
    })
  }
}
