import http from 'k6/http'
import { check } from 'k6'

// Shared across all six stacks per CLAUDE.md §5 — do not fork per-stack copies.
// Mix: 50% point-read, 20% paginated list, 30% write (matches the "70% reads /
// 30% writes" split from the spec, with reads further split across the two
// GET endpoints so both read paths get exercised).

const BASE_URL = __ENV.BASE_URL || 'http://localhost:8080'
const RATE = parseInt(__ENV.RATE || '50', 10)
const DURATION = __ENV.DURATION || '20s'
const SEED_ROWS = parseInt(__ENV.SEED_ROWS || '100000', 10)

export const options = {
  scenarios: {
    load: {
      executor: 'constant-arrival-rate',
      rate: RATE,
      timeUnit: '1s',
      duration: DURATION,
      preAllocatedVUs: Math.max(RATE * 2, 20),
      maxVUs: Math.max(RATE * 4, 50),
    },
  },
  // p(99) isn't in k6's default summary trend stats — the SLA (CLAUDE.md §4)
  // is defined in terms of it, so the orchestrator needs it in the exported JSON.
  summaryTrendStats: ['avg', 'min', 'med', 'max', 'p(90)', 'p(95)', 'p(99)'],
}

function randomInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min
}

export default function () {
  const roll = Math.random()

  if (roll < 0.5) {
    const id = randomInt(1, SEED_ROWS)
    const res = http.get(`${BASE_URL}/items/${id}`)
    check(res, { 'GET /items/:id status is 200': (r) => r.status === 200 })
  } else if (roll < 0.7) {
    const page = randomInt(1, Math.floor(SEED_ROWS / 20))
    const res = http.get(`${BASE_URL}/items?page=${page}&limit=20`)
    check(res, { 'GET /items status is 200': (r) => r.status === 200 })
  } else {
    const payload = JSON.stringify({
      name: `Load Item ${Date.now()}-${randomInt(0, 999999)}`,
      description: 'generated by k6 load test',
      price_cents: randomInt(100, 9999),
      quantity: randomInt(1, 100),
    })
    const res = http.post(`${BASE_URL}/items`, payload, {
      headers: { 'Content-Type': 'application/json' },
    })
    check(res, { 'POST /items status is 201': (r) => r.status === 201 })
  }
}
